"""add unique constraints

Revision ID: 44496a379dc4
Revises: d0db802c8b3a
Create Date: 2026-03-14 16:19:45.201309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44496a379dc4'
down_revision: Union[str, Sequence[str], None] = 'd0db802c8b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cloudtrail_events', 'event_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('cloudtrail_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cloudtrail_events_aws_region'), table_name='cloudtrail_events')
    op.drop_index(op.f('ix_cloudtrail_events_event_name'), table_name='cloudtrail_events')
    op.drop_index(op.f('ix_cloudtrail_events_event_source'), table_name='cloudtrail_events')
    op.drop_index(op.f('ix_cloudtrail_events_source_ip'), table_name='cloudtrail_events')
    op.drop_index(op.f('ix_cloudtrail_events_user_name'), table_name='cloudtrail_events')
    op.create_unique_constraint('uq_cloudtrail_event_id', 'cloudtrail_events', ['event_id'])
    op.create_unique_constraint('uq_guardduty_finding_id', 'guardduty_findings', ['finding_id'])
    op.create_unique_constraint('uq_vpc_flow_unique', 'vpc_flow_logs', ['src_addr', 'dst_addr', 'src_port', 'dst_port', 'start_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vpc_flow_unique', 'vpc_flow_logs', type_='unique')
    op.drop_constraint('uq_guardduty_finding_id', 'guardduty_findings', type_='unique')
    op.drop_constraint('uq_cloudtrail_event_id', 'cloudtrail_events', type_='unique')
    op.create_index(op.f('ix_cloudtrail_events_user_name'), 'cloudtrail_events', ['user_name'], unique=False)
    op.create_index(op.f('ix_cloudtrail_events_source_ip'), 'cloudtrail_events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_cloudtrail_events_event_source'), 'cloudtrail_events', ['event_source'], unique=False)
    op.create_index(op.f('ix_cloudtrail_events_event_name'), 'cloudtrail_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_cloudtrail_events_aws_region'), 'cloudtrail_events', ['aws_region'], unique=False)
    op.alter_column('cloudtrail_events', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cloudtrail_events', 'event_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
