"""initial tables

Revision ID: 6a9e9e114623
Revises: 
Create Date: 2026-03-14 13:56:29.864020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a9e9e114623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_account_id_start_time'), table_name='vpc_flow')
    op.drop_index(op.f('idx_is_suspicious_rejected'), table_name='vpc_flow')
    op.drop_index(op.f('idx_srcaddr_dstaddr'), table_name='vpc_flow')
    op.drop_index(op.f('idx_start_time_action'), table_name='vpc_flow')
    op.drop_index(op.f('ix_vpc_flow_account_id'), table_name='vpc_flow')
    op.drop_index(op.f('ix_vpc_flow_action'), table_name='vpc_flow')
    op.drop_index(op.f('ix_vpc_flow_dstaddr'), table_name='vpc_flow')
    op.drop_index(op.f('ix_vpc_flow_is_rejected'), table_name='vpc_flow')
    op.drop_index(op.f('ix_vpc_flow_is_suspicious'), table_name='vpc_flow')
    op.drop_index(op.f('ix_vpc_flow_srcaddr'), table_name='vpc_flow')
    op.drop_index(op.f('ix_vpc_flow_start_time'), table_name='vpc_flow')
    op.drop_table('vpc_flow')
    op.drop_index(op.f('idx_resource_id'), table_name='guardduty')
    op.drop_index(op.f('idx_severity_created'), table_name='guardduty')
    op.drop_index(op.f('idx_severity_level'), table_name='guardduty')
    op.drop_index(op.f('idx_type_account'), table_name='guardduty')
    op.drop_index(op.f('ix_guardduty_account_id'), table_name='guardduty')
    op.drop_index(op.f('ix_guardduty_created_at'), table_name='guardduty')
    op.drop_index(op.f('ix_guardduty_is_critical'), table_name='guardduty')
    op.drop_index(op.f('ix_guardduty_severity'), table_name='guardduty')
    op.drop_index(op.f('ix_guardduty_type'), table_name='guardduty')
    op.drop_table('guardduty')
    op.drop_index(op.f('idx_account_time'), table_name='cloudtrail')
    op.drop_index(op.f('idx_event_name_time'), table_name='cloudtrail')
    op.drop_index(op.f('idx_source_ip_time'), table_name='cloudtrail')
    op.drop_index(op.f('idx_suspicious_error'), table_name='cloudtrail')
    op.drop_index(op.f('idx_username_time'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_account_id'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_aws_region'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_error_code'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_event_name'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_event_source'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_eventid'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_eventtime'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_is_error'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_is_suspicious'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_source_ip_address'), table_name='cloudtrail')
    op.drop_index(op.f('ix_cloudtrail_username'), table_name='cloudtrail')
    op.drop_table('cloudtrail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloudtrail',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('eventid', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('eventtime', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('aws_region', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('principal_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source_ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('request_parameters', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_elements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_error', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_suspicious', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_api_call', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cloudtrail_pkey'))
    )
    op.create_index(op.f('ix_cloudtrail_username'), 'cloudtrail', ['username'], unique=False)
    op.create_index(op.f('ix_cloudtrail_source_ip_address'), 'cloudtrail', ['source_ip_address'], unique=False)
    op.create_index(op.f('ix_cloudtrail_is_suspicious'), 'cloudtrail', ['is_suspicious'], unique=False)
    op.create_index(op.f('ix_cloudtrail_is_error'), 'cloudtrail', ['is_error'], unique=False)
    op.create_index(op.f('ix_cloudtrail_eventtime'), 'cloudtrail', ['eventtime'], unique=False)
    op.create_index(op.f('ix_cloudtrail_eventid'), 'cloudtrail', ['eventid'], unique=True)
    op.create_index(op.f('ix_cloudtrail_event_source'), 'cloudtrail', ['event_source'], unique=False)
    op.create_index(op.f('ix_cloudtrail_event_name'), 'cloudtrail', ['event_name'], unique=False)
    op.create_index(op.f('ix_cloudtrail_error_code'), 'cloudtrail', ['error_code'], unique=False)
    op.create_index(op.f('ix_cloudtrail_aws_region'), 'cloudtrail', ['aws_region'], unique=False)
    op.create_index(op.f('ix_cloudtrail_account_id'), 'cloudtrail', ['account_id'], unique=False)
    op.create_index(op.f('idx_username_time'), 'cloudtrail', ['username', 'eventtime'], unique=False)
    op.create_index(op.f('idx_suspicious_error'), 'cloudtrail', ['is_suspicious', 'is_error'], unique=False)
    op.create_index(op.f('idx_source_ip_time'), 'cloudtrail', ['source_ip_address', 'eventtime'], unique=False)
    op.create_index(op.f('idx_event_name_time'), 'cloudtrail', ['event_name', 'eventtime'], unique=False)
    op.create_index(op.f('idx_account_time'), 'cloudtrail', ['account_id', 'eventtime'], unique=False)
    op.create_table('guardduty',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('severity_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_critical', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('finding_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('principal_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('principal_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at_db', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('guardduty_pkey'))
    )
    op.create_index(op.f('ix_guardduty_type'), 'guardduty', ['type'], unique=False)
    op.create_index(op.f('ix_guardduty_severity'), 'guardduty', ['severity'], unique=False)
    op.create_index(op.f('ix_guardduty_is_critical'), 'guardduty', ['is_critical'], unique=False)
    op.create_index(op.f('ix_guardduty_created_at'), 'guardduty', ['created_at'], unique=False)
    op.create_index(op.f('ix_guardduty_account_id'), 'guardduty', ['account_id'], unique=False)
    op.create_index(op.f('idx_type_account'), 'guardduty', ['type', 'account_id'], unique=False)
    op.create_index(op.f('idx_severity_level'), 'guardduty', ['severity_level'], unique=False)
    op.create_index(op.f('idx_severity_created'), 'guardduty', ['severity', 'created_at'], unique=False)
    op.create_index(op.f('idx_resource_id'), 'guardduty', ['resource_id'], unique=False)
    op.create_table('vpc_flow',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('interface_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('srcaddr', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('dstaddr', postgresql.INET(), autoincrement=False, nullable=False),
    sa.Column('srcport', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dstport', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('protocol', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('packets', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('start', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('end', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('log_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('traffic_direction', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_rejected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_suspicious', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('private_src', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('private_dst', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vpc_flow_pkey'))
    )
    op.create_index(op.f('ix_vpc_flow_start_time'), 'vpc_flow', ['start_time'], unique=False)
    op.create_index(op.f('ix_vpc_flow_srcaddr'), 'vpc_flow', ['srcaddr'], unique=False)
    op.create_index(op.f('ix_vpc_flow_is_suspicious'), 'vpc_flow', ['is_suspicious'], unique=False)
    op.create_index(op.f('ix_vpc_flow_is_rejected'), 'vpc_flow', ['is_rejected'], unique=False)
    op.create_index(op.f('ix_vpc_flow_dstaddr'), 'vpc_flow', ['dstaddr'], unique=False)
    op.create_index(op.f('ix_vpc_flow_action'), 'vpc_flow', ['action'], unique=False)
    op.create_index(op.f('ix_vpc_flow_account_id'), 'vpc_flow', ['account_id'], unique=False)
    op.create_index(op.f('idx_start_time_action'), 'vpc_flow', ['start_time', 'action'], unique=False)
    op.create_index(op.f('idx_srcaddr_dstaddr'), 'vpc_flow', ['srcaddr', 'dstaddr'], unique=False)
    op.create_index(op.f('idx_is_suspicious_rejected'), 'vpc_flow', ['is_suspicious', 'is_rejected'], unique=False)
    op.create_index(op.f('idx_account_id_start_time'), 'vpc_flow', ['account_id', 'start_time'], unique=False)
    # ### end Alembic commands ###
